server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: registry-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: registry-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
        - id: credits-personal-service
          uri: lb://credits-personal-service
          predicates:
            - Path=/api/credits/personal/**
        - id: bank-account-savings-service
          uri: lb://bank-account-savings-service
          predicates:
            - Path=/api/bank-account/savings/**
        - id: credit-card
          uri: lb://credit-card
          predicates:
            - Path=/api/credit-card/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/nttdata-final-project-realm
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
