spring:
  datasource:
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/bank-account-savings-service
  jpa:
    hibernate:
      ddl-auto: create-drop
  application:
    name: bank-account-savings-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka

server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: "*"