server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  datasource:
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/credits-personal-service
  jpa:
    hibernate:
      ddl-auto: create-drop
  application:
    name: credits-personal-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: notificationTopic
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: "event:com.nttdata.creditspersonalservice.event.PaidCreditEvent"

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: "*"